// Engine Quality Gate Orchestrator
// Coordinates Benchmark and Robustness suites, enforces hard gates, and exports JSON history.

import fs from 'fs';
import path from 'path';
import { runBenchmarkSuite } from './benchmark-multi-model';
import { runRobustnessSuite } from './robustness-validation';

const HISTORY_DIR = path.resolve(__dirname, 'history');
const VERSION = 'v45.3'; // Current version being validated
const BASELINE_PATH = path.join(HISTORY_DIR, 'baseline.json');
const LATEST_PATH = path.join(HISTORY_DIR, 'latest.json');

const FEATURES = {
  useStripLock: true,
  useSmartSplit: true,
  penalizeSmallLeftovers: true,
  useContinuityBonus: true,
  useGeometricContinuity: true,
  useBacktracking: true,
  useInvalidCache: true,
  enableV44BalancedMode: true,
  enableDepth1Lookahead: true,
  enableDepth1LookaheadV2: true,
  enableForcedConsumptionZone: true,
  enablePrimaryPanelAggression: true,
  enableStructuralPairClosure: true,
  enableComplementaryPoolAlignment: true,
  enableP2Aggression: true,
  deferredMassThreshold: 100000
};

async function validateEngine() {
  console.log(`=== ENGINE QUALITY GATE: ${VERSION} ===\n`);

  // 1. Run Suites
  console.log('Running Multi-Model Benchmark...');
  const models = runBenchmarkSuite(FEATURES);
  
  console.log('Running Robustness Validation (30 iterations)...');
  const robustness = runRobustnessSuite(FEATURES);

  // 2. Load Baseline (if exists)
  let baseline: any = null;
  if (fs.existsSync(BASELINE_PATH)) {
    baseline = JSON.parse(fs.readFileSync(BASELINE_PATH, 'utf-8'));
    console.log(`Comparing against baseline: ${baseline.version}`);
  } else {
    console.log('Warning: No baseline.json found. Comparing against self (initialization mode).');
  }

  // 3. Evaluate Hard Gates
  const hardGates = {
    panelCountStable: true,
    noNewNoodles: true,
    robustnessPass: true,
    performanceWithinLimit: true
  };

  const summary = {
    panelCountRegressions: 0,
    p1AverageDelta: 0,
    totalEfficiencyAverageDelta: 0,
    noodleRegressions: 0,
    performanceDeltaMs: 0
  };

  // Model comparison
  models.forEach(model => {
    const baseModel = baseline?.models?.find((m: any) => m.id === model.id);
    if (baseModel) {
      if (model.result.panelCount > baseModel.result.panelCount) {
        hardGates.panelCountStable = false;
        summary.panelCountRegressions++;
      }
      if (model.result.noodleCount > baseModel.result.noodleCount) {
        hardGates.noNewNoodles = false;
        summary.noodleRegressions++;
      }
      summary.p1AverageDelta += (model.result.p1Efficiency - baseModel.result.p1Efficiency);
      summary.totalEfficiencyAverageDelta += (model.result.totalEfficiency - baseModel.result.totalEfficiency);
      summary.performanceDeltaMs += (model.result.executionTimeMs - baseModel.result.executionTimeMs);
    }
  });
  summary.p1AverageDelta /= models.length;
  summary.totalEfficiencyAverageDelta /= models.length;
  summary.performanceDeltaMs /= models.length;

  if (robustness.shuffle.successRate < 1.0) hardGates.robustnessPass = false;
  if (summary.performanceDeltaMs > 100) hardGates.performanceWithinLimit = false;

  const verdict = (hardGates.panelCountStable && hardGates.noNewNoodles && hardGates.robustnessPass) ? 'PASS' : 'FAIL';

  // 4. Generate Snapshot
  const snapshot = {
    version: VERSION,
    createdAt: new Date().toISOString(),
    baselineComparedAgainst: baseline?.version || 'none',
    verdict,
    summary,
    hardGates,
    models,
    robustness,
    engineFeatures: FEATURES,
    notes: [
      "Auto-generated by validate-engine.ts",
      verdict === 'PASS' ? "Meets all industrial stability criteria." : "Regressions detected. Check model deltas."
    ]
  };

  // 5. Save Results
  if (!fs.existsSync(HISTORY_DIR)) fs.mkdirSync(HISTORY_DIR, { recursive: true });
  const resultPath = path.join(HISTORY_DIR, `${VERSION}.json`);
  fs.writeFileSync(resultPath, JSON.stringify(snapshot, null, 2));
  fs.writeFileSync(LATEST_PATH, JSON.stringify(snapshot, null, 2));

  // 6. Console Report
  console.log('\n--- VALIDATION SUMMARY ---');
  console.log(`Verdict: ${verdict === 'PASS' ? '✅ PASS' : '❌ FAIL'}`);
  console.log(`Panels: ${summary.panelCountRegressions === 0 ? 'Stable' : `${summary.panelCountRegressions} REGRESSIONS`}`);
  console.log(`P1 Avg Delta: ${summary.p1AverageDelta.toFixed(2)}%`);
  console.log(`Robustness Score: ${(robustness.shuffle.successRate * 100).toFixed(0)}%`);
  console.log(`Snapshot saved to: src/test-optimizer/history/${VERSION}.json`);
}

validateEngine().catch(err => {
  console.error('Validation failed:', err);
  process.exit(1);
});
